### ISSUE TITLE
How to get blocked list

### ISSUE THREAD

**Issue by mm580486** [rack/rack-attack#478]
hi
i searched in document but i cant find anything about list of blocked ip or safe list ip 
i want to show this lists for admin user

**Comment by shiralwz** [comment]
Hi Same questions here, how to get safelist and blocklist
@grzuy

**Comment by Mihoid** [comment]
@mm580486 @shiralwz 
`Rack::Attack.blocklists`
`Rack::Attack.safelists`

**Comment by grzuy** [comment]
Thanks @Mih
