### ISSUE TITLE
Rack Attack Gets Ingress IP not Remote Client IP

### ISSUE THREAD

**Issue by sephethus** [rack/rack-attack#489]
We've got this set up in a GKE cluster on the GCP public cloud. The cluster has an nginx controller installed. Why is the IP returned in the logs getting the ingress IP rather than the IP of the external user who's hitting the website, whether on the VPN or not.  We have two internal VPN addresses that we allow connections from. Here is the config we have. So how can we get the real IP of the remote user?
```
# frozen_string_literal: true

Rack::Attack.safelist('request is coming from a BDT employee\'s home') do |request|
  # TODO: Fix split vpn and dns tunneling so access to kayak is forced through
  # then network again. The remove this safelisting rule because it could be
  # accidentally granting access to thousands of NATed ISP customers.

Rack::Attack.safelist('request is coming from BDT\'s network') do |request|
   ['[vpn IP 1]', '[vpn IP 2]'].include?(request.ip)
end

Rack::Attack.safelist('The application is not in production') do |_request|
  !Rails.env.production?
end

Rack::Attack.safelist('the request is coming from a private ip') do |request|
  [
    IPAddr.new('192.168.0.0/16'),
    IPAddr.new('172.16.0.0/12'),
    IPAddr.new('10.0.0.0/8'),
    IPAddr.new('127.0.0.1')
  ].any? { |r| r.include?(request.ip) }
end

Rack::Attack.safelist('the request going to the campaign executions API') do |request|
  request.path.match?(/\/api\/campaigns\/\d+\/campaign_executions/)
end

Rack::Attack.blocklist('block all access to kayak') do |request|
  IPAddr.new('0.0.0.0/0').include?(request.ip)
end

ActiveSupport::Notifications.subscribe('blocklist.rack_attack') do |name, start, finish, request_id, payload|
  Rails.logger.error(name)
  Rails.logger.error(payload[:request].ip)
end
```

**Comment by patrykwojtynski** [comment]
Prob this is an issue with your application config and `trusted_proxies`. Please take a look at that: https://github.com/jetstack/kube-lego/issues/57

**Comment by grzuy** [comment]
Hi @sephethus, welcome.

I suspect this is out of rack-attack scope because rack-attack doesn't do anything special with the IP.

When you do `request.ip` in your configuration, all that's doing is calling [`Rack::Request#ip`](https://www.rubydoc.info/gems/rack/Rack/Request/Helpers#ip-instance_method) method, which looks for the `REMOTE_ADDR` HTTP header.

Hope that helps you in some way to find a solution.
