### ISSUE TITLE
Rspec test case: can't change ENV variable value using blocklist

### ISSUE THREAD

**Issue by shiralwz** [rack/rack-attack#497]
Could anyone share some blocklist test cases with an ENV variable as well, I found that in the spec file, we can't change the env variable in the rails middleware.

If we set the env variable in the spec file.
`stub_const('ENV', 'RACK_ATTACK_BLOCK_IP_LIST' => '1.1.1.1')`

in the application.yml file, there is a setting:
`RACK_ATTACK_BLOCK_IP_LIST: '2.2.2.2'`

If we run the test case and monitor env values in rake_attack.rb file,we can only get the new env variable value '1.1.1.1' in side safelist block, for example :
```
blocklist('block_ip_list') do |req|  
    block_ip_list = ENV['RACK_ATTACK_BLOCK_IP_LIST'].try(:split, /,\s*/) || []  
    block_ip_list.include?(req.ip)
end
```
if we move the safe_ip_list out of the safelist block, it will still '2.2.2.2'
```
block_ip_list = ENV['RACK_ATTACK_BLOCK_IP_LIST'].try(:split, /,\s*/) || []
blocklist('block_ip_list') do |req| 
   block_ip_list.include?(req.ip)
end
```

**Comment by shiralwz** [comment]
Here is the answer for my question:

the first line,  ```block_ip_list = ... ```    is run on initialization (before the spec runner even starts, before I stub the const). Whereas the fourth line, block_ip_list.include?(req.ip) is inside a procedure (do block) evidently run at a later time (and based on the results I'm getting, after I've stubbed the const).
the stub runs after initialization but before the block.

**Comment by grzuy** [comment]
Thank you!
