### ISSUE TITLE
throttle limitation not working immediately

### ISSUE THREAD

**Issue by shiralwz** [rack/rack-attack#498]
I set up every 30 seconds to allow 10 requests to reach /login, then we tested it by real http requests.  but I got the 429 response after 18s in 3 tps (around 50~60 hits), which is not very accurate.

**Comment by shiralwz** [comment]
We think it might be caused by multi unicore workers, we have 4 unicore workers, and it's not throttling each worker as you expect. We can still rate limit but need to also consider the number of dynos we have running when we configure the limits

**Comment by grzuy** [comment]
> I set up every 30 seconds to allow 10 requests to reach /login, then we tested it by real http requests. but I got the 429 response after 18s in 3 tps (around 50~60 hits), which is not very accurate.

Hi @shiralwz ,

This is not unexpected for the first period, per the current implementation of the throttle algorithm.
The first "throttling period or window" does not necessarily starts at the moment of the first request.

For what is worth, improving the throttling algorithm has been considered in the past: https://github.com/rack/rack-attack/issues/205.
