### ISSUE TITLE
Custom Response: add image

### ISSUE THREAD

**Issue by CarlosUvaSilva** [rack/rack-attack#499]
is it possible to add an image to the custom response text? I've tried to put and url put the url is sent as a normal string, is there a way to tell it to open the image link?
I'd imagine if using curl the link is not opened but if I try to trigger the blocked URL in a chrome window I could show the text + the image

Thank you

**Comment by grzuy** [comment]
Hi @CarlosUvaSilva, when setting a custom response you have the ability to to write whatever you want the HTTP response body to be. You have full control of that.

That means nothings stopping you to write any HTML you want the browser to render, including an `<img>` HTML tag.
