### ISSUE TITLE
Throttling with multiple discriminator

### ISSUE THREAD

**Issue by ctrlventure** [rack/rack-attack#500]
Is there a way to throttle based on multiple descriminators?
Basically my situation is that i have multiple sites that `proxy_pass` to one app so for example `domain1.com` translates to the route `/sites/:id_1/`, `domain2.com` to `/sites/:id_2/` and so on, so i how can i throttle for example requests to `domain1.com/authenticate` that won't affect `domain2.com/authenticate`?

Basically i would need to throttle based on the descriminator being not only the IP but also the site ID, is there any way to do this?

**Comment by grzuy** [comment]
Hi @ctrlventure ,

Discriminator can be anything you want.

An option can concatenating the site id and the ip into 1 discriminator.

```rb
  site_id = ... # whatever calculation of the site id based on the request object
  
  "#{site_id}-{request.id}"
end
```

or you can have just two separate throttles, each conditionally (based on the site id) returning the `request.ip`.
