### ISSUE TITLE
Remove option to allow more than 1 card per envelope in Recipient Choice settings in project

### ISSUE THREAD

**Issue by bmo** [rack/rack-attack#501]
<img width="872" alt="Screen Shot 2020-09-25 at 4 58 30 PM" src="https://user-images.githubusercontent.com/11912/94324818-77c3ab00-ff50-11ea-8b99-2691d71743f9.png">

**Comment by grzuy** [comment]
Apparently not related to rack-attack. Assuming this was posted in the wrong place by accident?
