### ISSUE TITLE
undefined method `throttled_callback=' for Rack::Attack:Class

### ISSUE THREAD

**Issue by somanwal** [rack/rack-attack#503]
I am using latest version 6.3.1 in which I am getting this error 

`undefined method `throttled_callback=' for Rack::Attack:Class`

When I checked in the installed gem code this method is actually not present. But in master branch this method is present. 

I want to use set custom header based on the request header in the response so I want `callback`. With `throttled_response` I am able to set header in `throttled_response` but there I can't access request object.

**Comment by Nowaker** [comment]
https://github.com/rack/rack-attack/issues/487
