### ISSUE TITLE
Latest published does not work on Ruby 3.0, master works fine

### ISSUE THREAD

**Issue by venables** [rack/rack-attack#515]
The latest version Rack::Attack published on rubygems.org (6.3.1) does not work on Ruby 3.0, but the master branch (with this fix: https://github.com/rack/rack-attack/pull/509) works just fine.  

Can you please cut a new release so we don't have to track against github?

**Comment by grzuy** [comment]
> The latest version Rack::Attack published on rubygems.org (6.3.1) does not work on Ruby 3.0, but the master branch (with this fix: #509) works just fine.

Indeed.
Thank you very much for reporting.

> 
> Can you please cut a new release so we don't have to track against github?

This is high priority issue, so yes, soon.

**Comment by grzuy** [comment]
Will release v6.4 after TravisCI goes green https://travis-ci.org/github/rack/rack-attack/builds/755855523.

**Comment by grzuy** [comment]
Fixed in `v6.4`.

Thanks again.

**Comment by grzuy** [comment]
> Will release v6.4 after TravisCI goes green https://travis-ci.org/github/rack/rack-attack/builds/755855523.

For what is worth, ended up regression testing locally with `wwtd`. Travis jobs were still queued and delayed after several hours.
