### ISSUE TITLE
Redis pipelining deprecation errors

### ISSUE THREAD

**Issue by leo3po** [rack/rack-attack#576]
Our logs are getting filled up with deprecation errors, please take a look.

<img width="1289" alt="Screenshot 2022-03-09 at 11 26 26" src="https://user-images.githubusercontent.com/20108458/157412826-1d8109cb-1cef-4010-aaed-05b595e68401.png">

**Comment by bnekolny** [comment]
I'm curious what came of this? Did you find something that caused you to close?

**Comment by leo3po** [comment]
It's been fixed https://github.com/rack/rack-attack/blob/main/lib/rack/attack/store_proxy/redis_proxy.rb
