### ISSUE TITLE
Rack 3 Support

### ISSUE THREAD

**Issue by fullmetalengineer** [rack/rack-attack#596]
Hi all,

I was looking to upgrade to Rack 3.0, but can't as rack-attack's `6.6.1` depends on `(rack>= 1.0, <3)`. I know there were some major changes to the Rack 3.0 upgrade, so I figured I would make an issue to get Rack 3 compatibility on the radar.

**Comment by grzuy** [comment]
Thanks.

This is in progress in https://github.com/rack/rack-attack/pull/586, although not clear in the title (which will update).

**Comment by gastonmorixe** [comment]
update on this?

**Comment by fayeroske** [comment]
plus one, any updates?

**Comment by ioquatix** [comment]
Sorry for the long delay on this, it fell off my radar and I've had a lot on my plate recently.

I've released v6.7.0 which should be compatible.

If you are a company and you want me to spend more time maintaining this gem, please consider sponsoring me: https://github.com/sponsors/ioquatix
