### ISSUE TITLE
The CHANGELOG seems to be missing info about v6.7.0

### ISSUE THREAD

**Issue by floehopper** [rack/rack-attack#616]

**Comment by RichStone** [comment]
Isn't this repository missing the v6.7.0 altogether?

**Comment by floehopper** [comment]
Yeah - the gem has been published but no release/tag and no changelog entry.

@ioquatix It looks like you did the version bump - do you know what's going on? Thanks!

**Comment by ioquatix** [comment]
https://github.com/rack/rack-attack/releases/tag/v6.7.0

If anyone has time/inclination to update the changelog, a PR would be great. Otherwise, we can just use those release notes. I'm fine with either.
