### ISSUE TITLE
Cache Store Down Policy

### ISSUE THREAD

**Issue by jessehanley** [rack/rack-attack#669]
Hey friends — is there an easy way to configure rack-attack to stay up if the cache store is down (i.e memcache cluster blows up)? If no, worth doing a PR for it? Quick glance at repo it seems nah.

**Comment by santib** [comment]
Hi @jessehanley, would you mind explaining what you have in mind as the "Cache Store Down Policy"? I mean, how would it work and how would it be an improvement compared to the current behavior?

Thank you!

**Comment by jessehanley** [comment]
Hey @santib! Cache store goes down >>> app continues running at all the throttled endpoints.

**Comment by jessehanley** [comment]
Can confirm!

**Comment by santib** [comment]
Thank you
